# Generated by Django 4.2.15 on 2024-08-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0002_alter_entry_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypp.name'),
        ),
    ]
