# Generated by Django 4.2.15 on 2024-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
