# Generated by Django 4.2.15 on 2024-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0005_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='number',
            new_name='quentity',
        ),
    ]
