# Generated by Django 4.2.15 on 2024-11-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0006_rename_number_storage_quentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
