# Generated by Django 4.2.15 on 2024-11-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0007_rename_quentity_storage_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='storage_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.storage'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='service',
            field=models.CharField(choices=[('طباعة', 'طباعة'), ('تصوير', 'تصوير'), ('سكان', 'سكان'), ('تقديم', 'تقديم'), ('بضاعة', 'بضاعة'), ('أخرى', 'أخرى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
