# Generated by Django 4.2.15 on 2024-12-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0009_selleditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleditems',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.storage'),
        ),
    ]
