# Generated by Django 4.2.15 on 2024-12-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0010_alter_selleditems_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleditems',
            old_name='name',
            new_name='item',
        ),
    ]
