# Generated by Django 4.2.15 on 2024-12-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0012_selleditems_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selleditems',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sold Item', 'verbose_name_plural': 'Sold Items'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['name'], 'verbose_name': 'Storage Item', 'verbose_name_plural': 'Storage Items'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='arabic_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='selleditems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='tapp.storage', verbose_name='Sold Item'),
        ),
        migrations.AlterField(
            model_name='selleditems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='selleditems',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity Sold'),
        ),
        migrations.AlterField(
            model_name='selleditems',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sale Timestamp'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity in Stock'),
        ),
    ]
